# Generated by Django 3.0.4 on 2020-03-14 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mywebsite_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Projects',
            new_name='Project',
        ),
    ]
