# Generated by Django 3.0.4 on 2020-03-14 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywebsite_app', '0003_auto_20200314_1006'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='text',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='link_to_project',
            new_name='link',
        ),
        migrations.AddField(
            model_name='project',
            name='name',
            field=models.CharField(default='Project name', max_length=100),
        ),
    ]
