# Generated by Django 3.0.4 on 2020-03-18 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywebsite_app', '0007_auto_20200318_1002'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='github_link',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='other_link',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
