# Generated by Django 3.0.4 on 2020-03-19 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywebsite_app', '0010_remove_project_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='github_link',
            field=models.CharField(blank=True, default='Repo name only', max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='other_link',
            field=models.CharField(blank=True, default='Domain without https://', max_length=100),
        ),
    ]
